# Install BIND (DNS server) as service on the (CentOS) host.
# configure DNS zones ("normal" and reverse) for the cluster.
---
- name: Ensure BIND is installed
  yum:
    name: ["bind", "bind-utils"]
    state: present

- name: Ensure BIND config file is up to date
  template: src=named.conf.j2 dest=/etc/named.conf
  notify:
    - reboot

- name: Ensure Zone files are in place
  template: src={{ item.src }} dest=/var/named/{{ item.dest }}
  with_items:
    - { src: "stackable.zone.j2", dest: "stackable.zone"}
    - { src: "stackable-reverse.zone.j2", dest: "stackable-reverse.zone"}
  notify:
    - reboot

- name: Ensure BIND is running and starting on boot
  service: 
    name: named 
    state: started
    enabled: yes