---
- hosts: all
  roles:
  - distribute_ssh_keys
- hosts: edge
  roles: 
  - centos_epel_8
  - role: edge_ip_forwarding
    when: not (wireguard|bool)
  - role: edge_ip_forwarding_for_wireguard
    when: wireguard|bool
  - role: edge_wireguard_host
    when: wireguard|bool
  - edge_bind
- hosts: protected
  roles:
  - protected_node_common_centos
  - protected_node_network_manager_dns_overwrite_disabled
  - protected_node_edge_as_dns
  - protected_node_mutual_access
  - protected_node_software_centos_8
  - protected_node_chrony
  - k9s
  - stackable_repo_centos_8
- hosts: orchestrators  
  roles:
  - wait
  - k3s_server
#  - stackable_operators
#  - stackable_collect_versions_operators
- hosts: nodes
  roles:
   - k3s_agent
   - kubeconfig
#- hosts: orchestrators  
#  roles:
#  - stackable_deploy_services
#- hosts: localhost
#  roles:
#  - merge_version_info
