---
- hosts: all
  roles:
  - distribute_ssh_keys
  - firewalld
- hosts: nat
  roles: 
  - centos_epel
  - nat_iptables_centos
  - nat_dns_centos
  - nat_wireguard_centos
- hosts: protected
  roles:
  - protected_node_common_centos
  - protected_node_configure_network
  - protected_node_mutual_access
  - protected_node_software_centos
  - protected_node_chrony
  - k9s
  - stackable_repo_centos
- hosts: orchestrators  
  roles:
  - wait
  - stackable_k3s  
  - stackable_operators
- hosts: nodes
  roles:
  - stackable_kubeconfig
  - stackable_agent
- hosts: orchestrators  
  roles:
  - stackable_approve_agents
  - stackable_deploy_services
- hosts: nat
  roles:
  - merge_version_info
