# Ensure Stackable operators are installed
---
- name: Install Stackable Helm-repos
  shell: |
    helm repo add stackable-dev https://repo.stackable.tech/repository/helm-dev/
    helm repo add stackable-stable https://repo.stackable.tech/repository/helm-stable/
    helm repo add stackable-test https://repo.stackable.tech/repository/helm-test/

- name: Update Helm repositories
  shell: |
    helm repo update

- name: install operators (when specific version is set)
  shell: |
    helm --kubeconfig kubeconfig --namespace default install stackable-{{ item }} {{stackable_component_versions[item]['repository']}}/{{ item }} --version '{{stackable_component_versions[item]['version']}}' || true
  loop: "{{ stackable_operators }}"
  when: 
    - item in stackable_component_versions.keys()
    - "'NONE' not in stackable_component_versions[item]['version']"

- name: install operators (from default version, _-operator)
  shell: |
    helm --kubeconfig kubeconfig --namespace default install stackable-{{ item }} {{stackable_component_versions['_-operator']['repository']}}/{{ item }} --version '{{stackable_component_versions['_-operator']['version']}}' || true
  loop: "{{ stackable_operators }}"
  when: 
    - item not in stackable_component_versions.keys()
    - "'_-operator' in stackable_component_versions.keys()"
    - "'NONE' not in stackable_component_versions['_-operator']['version']"

- name: install operators (nothing specified, install RELEASE)
  shell: |
    helm --kubeconfig kubeconfig --namespace default install stackable-{{ item }} stackable-stable/{{ item }} || true
  loop: "{{ stackable_operators }}"
  when: 
    - item not in stackable_component_versions.keys()
    - "'_-operator' not in stackable_component_versions.keys()"

