---
- name: Install operator (YUM)
  yum:
    name: "{{ stackable_package_versions[item.name] | default(item.service) }}"
    state: present
  loop: "{{ stackable_operators }}"
  notify: restart operators
  when: 
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")

- name: Install operator (APT)
  apt:
    name: "{{ stackable_package_versions[item.name] | default(item.service) }}"
    state: present
    force: yes
  loop: "{{ stackable_operators }}"
  notify: restart operators
  when: 
    - ansible_distribution == "Debian"

- name: Create directory for drop-in file for operator service
  file:
    path: /lib/systemd/system/{{ item.service }}.service.d/
    state: directory
  loop: "{{ stackable_operators }}"

- name: Add drop-in file for operator service to run under stackable-user
  template:
    src: service-user.j2
    dest: /lib/systemd/system/{{ item.service }}.service.d/service-user.conf
  loop: "{{ stackable_operators }}"
  notify: restart operators

- name: Apply CRDs
  shell: "{{ item.crd_command }}"
  args:
    warn: no
  loop: "{{ stackable_operators }}"
