---
- name: Install operator (YUM)
  yum:
    name: "{{ stackable_package_versions[item.name] | default(item.service) }}"
    state: present
  loop: "{{ stackable_operators }}"
  notify: restart operators
  when: 
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")

- name: Install operator (APT)
  apt:
    name: "{{ stackable_package_versions[item.name] | default(item.service) }}"
    state: present
    force: yes
  loop: "{{ stackable_operators }}"
  notify: restart operators
  when: 
    - ansible_distribution == "Debian"

- name: Apply CRDs
  shell: "{{ item.crd_command }}"
  args:
    warn: no
  loop: "{{ stackable_operators }}"
