# Ensure Stackable operators are installed
---
- name: Install Stackable Helm-repos
  shell: |
    helm repo add stackable-dev https://repo.stackable.tech/repository/helm-dev/
    helm repo add stackable-stable https://repo.stackable.tech/repository/helm-stable/
    helm repo add stackable-test https://repo.stackable.tech/repository/helm-test/
  args:
    warn: no
  vars:
    ansible_become: false
  when: "'localhost' not in inventory_hostname"

- name: Update Helm repositories
  shell: |
    helm repo update
  vars:
    ansible_become: false

- name: install operators (when version is set)
  shell: |
    helm install stackable-{{ item }} {{stackable_component_versions[item]['repository']}}/{{ item }} --version '{{stackable_component_versions[item]['version']}}' || true
  loop: "{{ stackable_operators }}"
  when: 
    - "'localhost' not in inventory_hostname"
    - item in stackable_component_versions.keys()
  vars:
    ansible_become: false

- name: install operators (when version is set, using kubeconfig from localhost)
  shell: |
    helm --kubeconfig resources/kubeconfig install stackable-{{ item }} {{stackable_component_versions[item]['repository']}}/{{ item }} --version '{{stackable_component_versions[item]['version']}}' || true
  loop: "{{ stackable_operators }}"
  when: 
    - "'localhost' in inventory_hostname"
    - item in stackable_component_versions.keys()
  vars:
    ansible_become: false

- name: install operators (when no version is set)
  shell: |
    helm install stackable-{{ item }} stackable-stable/{{ item }} || true
  loop: "{{ stackable_operators }}"
  when: 
    - "'localhost' not in inventory_hostname"
    - item not in stackable_component_versions.keys()
  vars:
    ansible_become: false

- name: install operators (when no version is set, using kubeconfig from localhost)
  shell: |
    helm --kubeconfig resources/kubeconfig install stackable-{{ item }} stackable-stable/{{ item }} || true
  loop: "{{ stackable_operators }}"
  when: 
    - "'localhost' in inventory_hostname"
    - item not in stackable_component_versions.keys()
  vars:
    ansible_become: false
