# Ensure Stackable operators are installed
---
- name: Install Stackable Helm-repos
  shell: |
    helm repo add stackable-dev https://repo.stackable.tech/repository/helm-dev/
    helm repo add stackable-stable https://repo.stackable.tech/repository/helm-stable/
  args:
    warn: no

- name: install operators (when version is set)
  shell: |
    helm install stackable-{{ item }} {{stackable_component_versions[item]['repository']}}/{{ item }} --version '{{stackable_component_versions[item]['version']}}' || true
  loop: "{{ stackable_operators }}"
  when: item in stackable_component_versions.keys()

- name: install operators (when no version is set)
  shell: |
    helm install stackable-{{ item }} stackable-stable/{{ item }} || true
  loop: "{{ stackable_operators }}"
  when: item not in stackable_component_versions.keys()

- name: Collect version info into file on server
  shell: |
    helm list > /tmp/stackable-versions.txt
  ignore_errors: True

- name: Fetch version info file to Ansible localhost
  fetch:
    src: /tmp/stackable-versions.txt
    dest: resources/stackable-versions.txt
    flat: yes
