# This file can be used with VS Code's REST Client Plugin (humao.rest-client)

# Define Host


@protocol = http
@host = localhost
@port = :8080
# redefine if necessary
#@host = t2.stackable.tech
#@port =
#@protocol = https

###

# List all clusters
{{protocol}}://{{host}}{{port}}/api/clusters

###

# broken UUID
{{protocol}}://{{host}}{{port}}/api/clusters/this-is-no-uuid

###

# UUID (syntax OK)
{{protocol}}://{{host}}{{port}}/api/clusters/b1015183-1835-4850-908c-796ac9ddf722

###

# UUID exists (please paste existing UUID)
{{protocol}}://{{host}}{{port}}/api/clusters/534d85b1-32e8-411b-98f9-08d5d5e3a6e2

###

# create new cluster
POST {{protocol}}://{{host}}{{port}}/api/clusters
t2-token: t2-secret-token

###

# delete cluster
DELETE {{protocol}}://{{host}}{{port}}/api/clusters/1d1e0888-0514-41aa-8abc-d319a41ceb08



