---
- name: Ensure operator is installed (YUM)
  yum:
    name: "stackable-{{ operator }}-operator-server-{{ version }}"
    state: present
    allow_downgrade: yes
    update_cache: yes
  when: 
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")

- name: Ensure operator is installed (APT)
  apt:
    name: "stackable-{{ operator }}-operator-server={{ version }}"
    state: present
    force: yes
    update_cache: yes
  when: 
    - ansible_distribution == "Debian"

- name: Restart operator
  systemd:
    name: "stackable-{{ operator }}-operator-server"
    state: restarted
    enabled: yes
    daemon_reload: yes