# Distribute the SSH keys provided in the cluster.yaml as authorized key to access this host.
---
- name: Distribute SSH public keys to server
  authorized_key:
    user: "{{ansible_user}}"
    state: present
    key: "{{ item }}"
  with_items: "{{ ssh_client_keys if ssh_client_keys is iterable else [] }}"