---
- name: create resources directory
  file:
    path: "resources"
    state: directory

- name: Create access file for a self-contained kubeconfig
  script: access_file_kubeconfig.py
  args:
    executable: python3