---
- name: Ensure stackable agent is installed
  yum:
    name: "stackable-agent-*nightly.el8.x86_64"
    state: present
  notify: restart agent

- name: Create directory for drop-in file for operator service
  file:
    path: /lib/systemd/system/stackable-agent.service.d/
    state: directory

- name: Add drop-in file for agent service
  template: 
    src: service-drop-in.j2 
    dest: /lib/systemd/system/stackable-agent.service.d/service.conf
  notify: restart agent

# These certificates are fake ones. We had problems with the AWS EKS cluster:
# It does not sign our CSR (certificate signing requests), the controller
# responsible for doing so is explicitly disabled in an AWS EKS cluster :-(
# With these certificates, the agents start up and do their job. It ist not quite
# clear how the fake certificates affect the ability to request the logs via the agents... (TODO)
- name: Create directory for certificate for agent
  file:
    path: /etc/stackable/stackable-agent/secret
    state: directory

- name: Copy certificate and key to agents
  copy:
    src: "{{ item }}"
    dest: /etc/stackable/stackable-agent/secret/
    owner: root
    group: root
    mode: 0400
  with_items: 
    - "agent.crt"
    - "agent.key"

