spring:
  main:
    banner-mode: "off"
server:
  error:
    include-stacktrace: never
t2:
  displayVersion: ${T2_DISPLAY_VERSION:}
  build:
    version: "@git.commit.id.describe-short@"
    timestamp: "@maven.build.timestamp@"
  workspace:
    directory: /tmp/t2-workspace/
  templates:
    directory: templates/
  security:
    token-file: security-token
    credential-file: ~/t2-credentials.properties
  dns:
    enabled: false
    cluster-domain: stackable.tech
    livedns-api-url: https://api.gandi.net/v5/livedns
