---
spring:
  main:
    banner-mode: "off"
---
server:
  error:
    include-stacktrace: never
---
t2:
  displayVersion: ${T2_DISPLAY_VERSION:}
  build:
    version: "@git.commit.id.describe-short@"
    timestamp: "@maven.build.timestamp@"
  workspace:
    directory: /tmp/t2-workspace/
  templates:
    directory: templates/
  security:
    token: t2-secret-token
    tool-init-script: tool-init.sh
---
management:
  endpoint:
    prometheus:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus