server:
  port: 8080
t2:
  workspace:
    directory: /var/t2/workspace/  
  templates:
    directory: /var/t2/templates/
  security:
    token-file: /var/t2/security-token
    credential-file: /var/t2/credentials.properties
