server:
  port: 8080
t2:
  workspace:
    directory: /var/t2/workspace/  
  templates:
    directory: /var/t2/templates/
  security:
    token: ${SECURITY_TOKEN}
    tool-init-script: /var/t2/tool-init.sh
