# Ensure the system is up to date and install useful stuff on CentOS 7
---
- name: Ensure system is up to date
  yum:
    name: "*"
    state: latest

- name: Ensure important and useful packages are installed
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - chrony
      - libselinux-python
      - man
      - tmux
      - vim-enhanced
      - wget
      - java-11-openjdk-devel
      - gnupg
      - tar
    
- name: Add Kubernetes repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
