---
- name: Ensure kubectl is installed
  package:
    name: kubectl
    state: present

- name: kubeconfig for the user - create directory
  file:
    path: ~/.kube
    state: directory
  vars:
    ansible_become: false

- name: kubeconfig for the Stackable user - copy file
  copy:
    src: "resources/kubeconfig"
    dest: "~/.kube/config"
  vars:
    ansible_become: false

- name: kubeconfig for the Stackable components - create directory
  file:
    path: /opt/stackable/
    state: directory

- name: kubeconfig for the Stackable components - copy file
  copy:
    src: "resources/kubeconfig"
    dest: "/opt/stackable/kubeconfig"
    mode: 0444
