---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: ionos-centos-8
metadata: 
  name: t2-integration-tests
  description: "Cluster for T2 Integration Tests (IONOS / CentOS 8)"
domain: stackable.test
publicKeys: []
spec:
  region: de/fra
  wireguard: false
  nodes:
    main:
      numberOfNodes: 1
      numberOfCores: 2
      memoryMb: 4096
      diskType: HDD 
      diskSizeGb: 15
    testdriver:
      numberOfNodes: 1
      numberOfCores: 2
      memoryMb: 4096
      diskType: HDD 
      diskSizeGb: 15
      k8s_node: false
