# Ensure Vector is installed and logging to T2 logging cluster
---
- name: Install Vector Helm-repos
  shell: |
    helm repo add vector https://helm.vector.dev/ --force-update
  args:
    warn: no

- name: Update Helm repositories
  shell: |
    helm repo update

- name: Create namespace for cluster logging
  shell: |
    kubectl --kubeconfig kubeconfig apply -f {{role_path}}/files/namespace.yaml

- name: Set a configmap which contains the cluster metadata
  shell: |
    kubectl --kubeconfig kubeconfig create configmap cluster-metadata \
        --namespace t2-cluster-logging \
        --from-literal=T2_CLUSTER_ID="{{ cluster_id }}" \
        --from-literal=K8S_VERSION="{{ k8s_installed_version }}" \
        --from-literal=JENKINS_USER_ID="{{ metadata['annotations']['t2.stackable.tech/jenkins-user-id'] | default("unknown", true) }}" \
        --from-literal=JENKINS_USER_EMAIL="{{ metadata['annotations']['t2.stackable.tech/jenkins-user-email'] | default("unknown", true) }}" \
        --from-literal=JENKINS_USER="{{ metadata['annotations']['t2.stackable.tech/jenkins-user'] | default("unknown", true) }}" \
        --from-literal=CLOUD_VENDOR="{{ metadata['annotations']['t2.stackable.tech/cloud-vendor'] | default("unknown", true) }}" \
        --from-literal=K8S="{{ metadata['annotations']['t2.stackable.tech/k8s'] | default("unknown", true) }}" \
        --from-literal=NODE_OS="{{ metadata['annotations']['t2.stackable.tech/node-os'] | default("unknown", true) }}" || true

- name: Create the secret which contains the information about the t2 cluster logging endpoint
  shell: |
    kubectl --kubeconfig kubeconfig create secret generic cluster-logging-target \
        --namespace t2-cluster-logging \
        --from-literal=endpoint='{{ lookup('env', 'CLUSTER_LOGGING_ENDPOINT') }}' \
        --from-literal=user='{{ lookup('env', 'CLUSTER_LOGGING_USER') }}' \
        --from-literal=password='{{ lookup('env', 'CLUSTER_LOGGING_PASSWORD') }}' || true

- name: Create transform rules for vector
  shell: |
    kubectl --kubeconfig kubeconfig apply -f {{role_path}}/files/vector-agent-transforms.yaml

- name: Install Vector Agent
  shell: |
    helm --kubeconfig kubeconfig install vector-agent vector/vector \
        --version 0.18.0 \
        --namespace t2-cluster-logging \
        --values {{role_path}}/files/vector-agent-values.yaml \
        --wait

- name: Install Vector Aggregator
  shell: |
    helm --kubeconfig kubeconfig install vector-aggregator vector/vector \
        --version 0.18.0 \
        --namespace t2-cluster-logging \
        --values {{role_path}}/files/vector-aggregator-values.yaml \
        --wait

# In order to ship K8s events through our logging pipeline, we deploy a so called "eventrouter". 
# This project (https://github.com/vmware-archive/eventrouter) is discontinued by VMWare 
# but works fine for now.
#
# (RedHat/OpenShift seemed to have adopted the project, but in order to use their image, 
# you have to have a RedHat "pull secret" which I avoided for now because the fork currently 
# does not provide any added value)
- name: deploy eventrouter (prints K8s events to stdout to be collected by Vector)
  shell: |
    kubectl --kubeconfig kubeconfig apply -f {{role_path}}/files/eventrouter.yaml

