# This task configures the nameserver to be the bastion_host (by internal IP)
---
- name: Disable DNS overwrite by NetworkManager
  ini_file: 
    dest: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns 
    value: none
  notify:
    - reboot

- name: Make sure that the NetworkManager no longer tampers with our DNS
  meta: flush_handlers

- name: Create resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
