# Install the AWS ESB CSI driver for AWS clusters
#
# https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/#csi-migration-updates
#
# https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html
# https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html
# https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html
#
---
- name: Create an IAM OIDC provider for our cluster
  shell: eksctl utils associate-iam-oidc-provider --cluster {{ cluster_name }} --approve
  register: aws_csi_create_iam_oidc_provider

- debug: var=aws_csi_create_iam_oidc_provider.stdout_lines

- name: Creating the Amazon EBS CSI driver IAM role for service accounts
  shell: |
    eksctl create iamserviceaccount \
      --name ebs-csi-controller-sa \
      --namespace kube-system \
      --cluster {{ cluster_name }} \
      --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
      --approve \
      --role-only \
      --role-name AmazonEKS_EBS_CSI_DriverRole-{{ cluster_name }}
  register: aws_csi_create_iam_role

- debug: var=aws_csi_create_iam_role.stdout_lines

- name: Adding the Amazon EBS CSI add-on
  shell: |
    eksctl create addon \
      --name aws-ebs-csi-driver \
      --cluster {{ cluster_name }} \
      --service-account-role-arn arn:aws:iam::$(aws sts get-caller-identity | jq -r '.Account'):role/AmazonEKS_EBS_CSI_DriverRole-{{ cluster_name }} \
      --force
  register: aws_csi_create_addon

- debug: var=aws_csi_create_addon.stdout_lines



