# Ensures that K8s components are labelled
# (runs on localhost)
---
- name: Set label(s) on orchestrator
  shell: kubectl --kubeconfig kubeconfig label node --overwrite=true orchestrator.{{ domain }} location={{ hostvars['orchestrator']['location'] | default(none) }}
  when: "'orchestrators' in groups"

# This is for an inventory with a [node] list (K3s clusters)
- name: Set label(s) on nodes
  shell: kubectl --kubeconfig kubeconfig label node --overwrite=true {{ item }}.{{ domain }} location={{ hostvars[item]['location'] | default(none) }} node_size={{ hostvars[item]['node_size'] | default(none) }}
  loop: "{{ groups['nodes'] }}"
  when: "'nodes' in groups"

# This is for an inventory with a [node] list (mK8s clusters)
- name: Set label(s) on nodes
  shell: |
    kubectl --kubeconfig kubeconfig get nodes --no-headers \
      | grep -v orchestrator \
      | sort \
      | cut -d ' ' -f 1 \
      | awk '{print "kubectl --kubeconfig kubeconfig label node --overwrite=true "$1" location={{ location }} node_size={{ node_size }}"}' \
      | sh
  when: "'nodes' not in groups"
