---
- name: Create directory for service definitions
  file:
    path: /tmp/services/
    state: directory

- name: Copy service definitions to host
  copy:
    src: "{{ item }}"
    dest: "/tmp/services/"
    owner: "root"
    mode: 0600
  with_fileglob:
    - "../files/services/*.yaml"

- name: gather service definitions to be applied
  find:
    paths: "/tmp/services"
    patterns: '*'
    recurse: no
    file_type: file
  register: service_definitions

- name: Apply service definitions 
  shell: "/usr/local/bin/kubectl apply -f {{ item.path }}"
  args:
    warn: no
  with_items: "{{ service_definitions.files }}"
