# Sets the edge node as DNS server
# As this config might be reset at each reboot, we create a service to config the DNS at startup
---
- name: Create template resolv.conf
  template:
    src: resolv.conf.j2
    dest: /root/resolv.conf
    mode: 0755

- name: Create DNS config script
  template:
    src: dnsconf.sh.j2
    dest: /root/dnsconf.sh
    mode: 0755

- name: execute DNS config script
  shell: /root/dnsconf.sh

- name: Create action to run DNS config script after network comes up
  template:
    src: configure_dns.service.j2
    dest: /etc/systemd/system/configure_dns.service

- name: Enable service for next restart
  systemd:
    name: configure_dns
    enabled: yes
    daemon_reload: yes
