---
- name: install nginx
  package:
    name:
      - nginx
      - nginx-mod-stream
    state: present
  notify: restart nginx

- name: configure nginx
  template: 
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
