---
- hosts: all
  roles:
  - distribute_ssh_keys
- hosts: edge
  roles: 
  - centos_epel_8
  - role: edge_ip_forwarding_for_wireguard
    when: wireguard|bool
  - role: edge_wireguard_host
    when: wireguard|bool
- hosts: protected
  roles:
  - protected_node_common_centos
  - protected_node_mutual_access
  - protected_node_software_centos_8
  - protected_node_chrony
  - k9s
  - stackable_repo_centos_8
- hosts: orchestrators  
  roles:
  - wait
  - protected_node_network_manager_cloud_setup_disabled
  - stackable_k3s
  - stackable_operators
  - stackable_collect_versions_operators
- hosts: nodes
  roles:
  - stackable_kubeconfig
- hosts: orchestrators  
  roles:
  - stackable_deploy_services
- hosts: localhost
  roles:
  - merge_version_info
