# Disable transparent hugepages
---
- name: Ensure that Transparent Hugepages are disabled
  lineinfile:
    dest: /etc/default/grub
    line: GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX transparent_hugepage=never"
    state: present
  notify:
    - update grub
    - reboot
