# Collect version informations
---
- name: Collect cluster info into file on server
  shell: |
    kubectl --kubeconfig resources/kubeconfig get nodes > resources/stackable-versions.txt
    echo '' >> resources/stackable-versions.txt
    kubectl --kubeconfig resources/kubeconfig get nodes -o custom-columns=NAME:metadata.name,TAINTS:spec.taints,LOCATION:metadata.labels.location,NODE_LABEL:metadata.labels.node --sort-by=metadata.name >> resources/stackable-versions.txt
    echo '' >> resources/stackable-versions.txt
    echo '' >> resources/stackable-versions.txt
  ignore_errors: True

- name: Collect operator versions info into file on server
  shell: |
    helm --kubeconfig resources/kubeconfig list >> resources/stackable-versions.txt
  ignore_errors: True
