# Install and configure chrony service
# https://chrony.tuxfamily.org/
---
- name: Ensure Chrony uses correct NTP servers
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  notify: restart chronyd
