# Collect version information to file
---
- name: create resources directory
  file:
    path: "resources"
    state: directory

- name: Collect cluster info into file
  shell: |
    echo 'Stackable test cluster configuration:' > resources/cluster-info.txt
    echo '=====================================' >> resources/cluster-info.txt
    echo '' >> resources/cluster-info.txt
    echo 'Cloud vendor:               {{ metadata['annotations']['t2.stackable.tech/cloud-vendor'] | default("unknown", true) }}' >> resources/cluster-info.txt
    echo 'Kubernetes distro:          {{ metadata['annotations']['t2.stackable.tech/k8s'] | default("unknown", true) }}' >> resources/cluster-info.txt
    echo 'OS on Kubernetes nodes:     {{ metadata['annotations']['t2.stackable.tech/node-os'] | default("unknown", true) }}' >> resources/cluster-info.txt
    echo '' >> resources/cluster-info.txt
    echo '' >> resources/cluster-info.txt
    echo 'Kubernetes nodes:' >> resources/cluster-info.txt
    echo '-----------------' >> resources/cluster-info.txt
    echo '' >> resources/cluster-info.txt
    kubectl --kubeconfig kubeconfig get nodes >> resources/cluster-info.txt
    echo '' >> resources/cluster-info.txt
    kubectl --kubeconfig kubeconfig get nodes -o custom-columns=NAME:metadata.name,TAINTS:spec.taints,LOCATION:metadata.labels.location,NODE_SIZE:metadata.labels.node_size --sort-by=metadata.name >> resources/cluster-info.txt
    echo '' >> resources/cluster-info.txt
    echo '' >> resources/cluster-info.txt
    echo '' >> resources/cluster-info.txt
    echo 'Stackable operators:' >> resources/cluster-info.txt
    echo '--------------------' >> resources/cluster-info.txt
    echo '' >> resources/cluster-info.txt
    helm --kubeconfig kubeconfig --namespace default list >> resources/cluster-info.txt
  ignore_errors: True
