# Collect version information to file
---
- name: create resources directory
  file:
    path: "resources"
    state: directory

- name: Collect cluster info into file
  shell: |
    kubectl --kubeconfig kubeconfig get nodes > resources/stackable-versions.txt
    echo '' >> resources/stackable-versions.txt
    kubectl --kubeconfig kubeconfig get nodes -o custom-columns=NAME:metadata.name,TAINTS:spec.taints,LOCATION:metadata.labels.location,NODE_LABEL:metadata.labels.node,NODE_SIZE:metadata.labels.node_size --sort-by=metadata.name >> resources/stackable-versions.txt
    echo '' >> resources/stackable-versions.txt
    echo '' >> resources/stackable-versions.txt
  ignore_errors: True

- name: Collect operator versions info into file
  shell: |
    helm --kubeconfig kubeconfig --namespace default list >> resources/stackable-versions.txt
  ignore_errors: True
