---
- hosts: all
  vars_prompt:

    - name: ionos_username
      prompt: Username in IONOS cloud
      private: no

    - name: ionos_password
      prompt: Password in IONOS cloud

    - name: gandi_api_token
      prompt: API token for Gandi DNS services

    - name: aws_access_key
      prompt: API access key for Amazon Web Services (AWS)

    - name: aws_secret_access_key
      prompt: API secret access key for Amazon Web Services (AWS)

  tasks:

    - name: create credentials file
      copy:
        dest: /var/t2/credentials.properties
        content: |
          ionos_username = {{ ionos_username }}
          ionos_password = {{ ionos_password }}
          gandi_api_token = {{ gandi_api_token }}
          aws_access_key = {{ aws_access_key }}
          aws_secret_access_key = {{ aws_secret_access_key }}
        owner: t2
        group: t2
        mode: "0440"
