# Install K3s
---
- name: Install K3s Agent w/ rancher script
  shell: |
    curl -sfL https://get.k3s.io | \
      INSTALL_K3S_CHANNEL={{ k8s_version }} INSTALL_K3S_SKIP_SELINUX_RPM=true \
      K3S_TOKEN="{{ hostvars['orchestrator']['k3s_token'] }}" \
      K3S_URL="https://orchestrator.{{ domain }}:6443" \
      sh -s - \
      --node-ip {{ ansible_host }} \
      --flannel-iface {{ private_network_interface_name }}
  args:
    warn: no
  when: k8s_node | bool
