# Install K3s
---
- name: Install K3s Agent w/ rancher script
  shell: |
    curl -sfL https://get.k3s.io | \
      K3S_TOKEN="{{ hostvars['orchestrator']['k3s_token'] }}" \
      K3S_URL="https://orchestrator.{{ domain }}:6443" \
      sh -s - 
  args:
    warn: no

