# Install K3s
---
- name: Install K3s Agent w/ rancher script
  shell: |
    curl -sfL https://get.k3s.io | \
      INSTALL_K3S_VERSION="{{ k8s_version }}" \
      K3S_TOKEN="{{ hostvars['orchestrator']['k3s_token'] }}" \
      K3S_URL="https://orchestrator.{{ domain }}:6443" \
      sh -s - \
      --node-ip {{ ansible_host }}
  args:
    warn: no
  when: k8s_node | bool
