# Install K3s Agent
---
- name: Download K3s binary
  get_url:
    url: https://repo.stackable.tech/repository/misc/k3s/{{ k8s_requested_version | default("stable", true) }}/k3s
    dest: /usr/local/bin/k3s
    mode: 0755

- name: Install K3s Agent w/ rancher script
  shell: |
    curl -sfL https://get.k3s.io | \
      INSTALL_K3S_SKIP_SELINUX_RPM=true INSTALL_K3S_SKIP_DOWNLOAD=true \
      K3S_TOKEN="{{ hostvars['orchestrator']['k3s_token'] }}" \
      K3S_URL="https://orchestrator.{{ domain }}:6443" \
      sh -s - \
      --node-ip {{ ansible_host }} \
      --flannel-iface {{ private_network_interface_name }}
  args:
    warn: no
  notify: restart k3s-agent
