---
role: Aggregator
customConfig:
  api:
    address: 0.0.0.0:8686
    enabled: true
  sources:
    vector:
      address: 0.0.0.0:6000
      type: vector
      version: "2"
  transforms:
    # Some products yield empty log lines which we do not want in our system
    drop_void_records:
      type: filter
      inputs:
        - vector
      condition: 
        type: vrl
        source: ".level != null || .logger != null || .message != null"
    enriched_logs:
      type: remap
      inputs: 
        - drop_void_records
      source: |-
        .t2_cluster = get_env_var!("T2_CLUSTER_ID")
        .k8s_version = get_env_var!("K8S_VERSION")
        .jenkins_user_id = get_env_var!("JENKINS_USER_ID")
        .jenkins_user_email = get_env_var!("JENKINS_USER_EMAIL")
        .jenkins_user = get_env_var!("JENKINS_USER")
        .cloud_vendor = get_env_var!("CLOUD_VENDOR")
        .k8s_distribution = get_env_var!("K8S")
        .node_os = get_env_var!("NODE_OS")
        # Kubernetes version analysis
        .k8s_version_full = .k8s_version
        .temp_k8s_version, err = parse_regex(.k8s_version, r'(v)?(?P<major>[0-9]+)\.(?P<minor>[0-9]+)(\.(?P<fix>[0-9]*))?.*')
        if err == null {
          .k8s_major_version = .temp_k8s_version.major
          .k8s_minor_version = .temp_k8s_version.minor
          .k8s_fix_version = .temp_k8s_version.fix
          if .k8s_fix_version != null {
              .k8s_version = .k8s_major_version + "." + .k8s_minor_version + "." + .k8s_fix_version
          } else {
              .k8s_version = .k8s_major_version + "." + .k8s_minor_version
          }
        } else {
          .k8s_major_version = null
          .k8s_minor_version = null
          .k8s_fix_version = null
          .k8s_version = null
        }
        del(.temp_k8s_version)
  sinks:
    opensearch_out:
      type: elasticsearch
      inputs:
        - enriched_logs
      endpoint: "${OPENSEARCH_ENDPOINT}"
      mode: bulk
      bulk:
        action: index
        index: t2-product-%F
      # Do not send the type because it was removed in OpenSearch 2.0.0/
      # Elasticsearch 8.0
      suppress_type_name: true
      tls:
        verify_certificate: false
        verify_hostname: false 
      auth:
        strategy: basic
        user: "${OPENSEARCH_USERNAME}"
        password: "${OPENSEARCH_PASSWORD}"
envFrom:
  - configMapRef:
      name: cluster-metadata 
env:
  - name: OPENSEARCH_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: cluster-logging-target
        key: endpoint
  - name: OPENSEARCH_USERNAME
    valueFrom:
      secretKeyRef:
        name: cluster-logging-target
        key: user
  - name: OPENSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: cluster-logging-target
        key: password
