- name: Ensure system is up to date
  apt:
    name: "*"
    state: latest

- name: Ensure important and useful packages are installed
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - unzip
      - chrony
      - curl
      - dnsutils
      - man-db
      - tmux
      - openjdk-11-jdk
      - gnupg
      - sudo
