# Ensure the system is up to date and install useful stuff on Debian
---
- name: Ensure system is up to date
  apt:
    name: "*"
    state: latest

- name: Ensure important and useful packages are installed
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - unzip
      - chrony
      - curl
      - dnsutils
      - man-db
      - tmux
      - openjdk-11-jdk
      - gnupg
      - sudo
      - tar
      - apparmor
      - apparmor-utils

- name: Add key for Kubernetes repository
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
