# Wait for all nodes to be ready
---
- name: Wait for all k8s nodes to be ready (k3s)
  shell: kubectl wait --for=condition=Ready nodes --all --timeout=600s
  register: nodes_ready
  when: 
    - "'localhost' not in inventory_hostname"

- debug: var=nodes_ready.stdout_lines
  when: 
    - "'localhost' not in inventory_hostname"
