---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: ionos-centos-7
metadata: 
  name: t2-integration-tests
  description: "Cluster for T2 Integration Tests (IONOS / CentOS 7)"
domain: stackable.test
publicKeys: []
spec:
  region: de/fra
  wireguard: false
  nodes:
    main:
      numberOfNodes: 3
      numberOfCores: 2
      memoryMb: 4096
      diskType: HDD 
      diskSizeGb: 15
