---
- name: Ensure stackable agent is installed (YUM)
  yum:
    name: "{{ stackable_package_versions['stackable-agent'] | default('stackable-agent') }}"
    state: present
  when: 
    - stackable_agent | bool
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
  notify: restart agent

- name: Ensure stackable agent is installed (APT)
  apt:
    name: "{{ stackable_package_versions['stackable-agent'] | default('stackable-agent') }}"
    state: present
    force: yes
  when: 
    - stackable_agent | bool
    - ansible_distribution == "Debian"
  notify: restart agent

- name: Create directory for drop-in file for operator service
  file:
    path: /lib/systemd/system/stackable-agent.service.d/
    state: directory
  when: stackable_agent | bool

- name: Add drop-in file for agent service
  template: 
    src: service-drop-in.j2 
    dest: /lib/systemd/system/stackable-agent.service.d/service.conf
  notify: restart agent
  when: stackable_agent | bool

- name: Copy script to collect versions to server
  copy:
    src: "collect-stackable-versions.sh"
    dest: "/tmp/collect-stackable-versions.sh"
    mode: 0700

- name: Collect version info into file on server
  shell: "/tmp/collect-stackable-versions.sh"

- name: Fetch version info file to Ansible localhost
  fetch: 
    src: "/tmp/stackable-versions.txt"
    dest: "temp/stackable-versions/{{ inventory_hostname }}.txt"
    flat: yes

