---
- name: Ensure stackable agent is installed (YUM)
  yum:
    name: "{{ stackable_package_versions['stackable-agent'] | default('stackable-agent') }}"
    state: present
  when: 
    - stackable_agent | bool
    - ansible_distribution == "CentOS"

- name: Ensure stackable agent is installed (APT)
  apt:
    name: "{{ stackable_package_versions['stackable-agent'] | default('stackable-agent') }}"
    state: present
    force: yes
  when: 
    - stackable_agent | bool
    - ansible_distribution == "Debian"

- name: Start stackable agent
  systemd:
    name: stackable-agent
    state: started
    enabled: yes
    daemon_reload: yes
  when: stackable_agent | bool

- name: Copy script to collect versions to server
  copy:
    src: "collect-stackable-versions.sh"
    dest: "/tmp/collect-stackable-versions.sh"
    mode: 0700

- name: Collect version info into file on server
  shell: "/tmp/collect-stackable-versions.sh"

- name: Fetch version info file to Ansible localhost
  fetch: 
    src: "/tmp/stackable-versions.txt"
    dest: "temp/stackable-versions/{{ inventory_hostname }}.txt"
    flat: yes

