# Sets the default gateway.
# As this config might be reset at each reboot, we create a service to config the network at startup
---
- name: Create network config script
  template:
    src: configure_gateway.sh.j2
    dest: /root/configure_gateway.sh
    mode: 0755

- name: execute network config script
  shell: /root/configure_gateway.sh

- name: Create action to run after network comes up and add default route to gateway
  template:
    src: configure_gateway.service.j2
    dest: /etc/systemd/system/configure_gateway.service

- name: Create route for internet access
  systemd:
    name: configure_gateway
    state: started
    enabled: yes
    daemon_reload: yes

