# Ensure kubectl is installed
---
- name: Ensure kubectl is installed
  package:
    name: kubectl
    state: present

- name: kubeconfig for the user - create directory
  file:
    path: "{{ stackable_user_home }}.kube"
    state: directory
  vars:
    ansible_become: false

- name: kubeconfig for the Stackable user - copy file
  copy:
    src: resources/kubeconfig
    dest: "{{ stackable_user_home }}.kube/config"
    mode: 0600
  vars:
    ansible_become: false
