---
- name: create resources directory
  file:
    path: "resources"
    state: directory

- name: Create access file for an AWS EKS cluster
  script: access_file_aws.py
  args:
    executable: python3