---

# This is needed on CentOS/RHEL because otherwise the running kernel and the kernel-headers (installed as a dependency of wireguard)
# might differ in version numbers and that causes the wireguard kernel module compilation to fail
- name: Upgrade all packages so Kernel headers match
  apt:
    name: '*'
    state: latest
  notify: reboot

- name: Flush handler if needed
  meta: flush_handlers

- name: Ensure WireGuard repository exists
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present

- name: Ensure WireGuard is installed
  apt:
    name:
      - wireguard
      - wireguard-tools
    state: present

- name: Ensure WireGuard kernel module is installed
  modprobe:
    name: wireguard
    state: present
  register: wireguard_module_enabled
  until:  wireguard_module_enabled is succeeded
  retries: 10
  delay: 10
  failed_when: wireguard_module_enabled is failure

- name: Ensure WireGuard configuration file is up-to-date
  copy:
    src: ../files/wireguard_server.conf
    dest: "/etc/wireguard/wg.conf"
    owner: root
    group: root
    mode: 0600

- name: Ensure WireGuard is started and enabled
  service:
    name: "wg-quick@wg"
    state: started
    enabled: yes
