---
# The authentication idea is pretty blunt: 
# We have to transfer the AWS access keys (of a real person)
# to all our nodes and they all run under these credentials.
# We should think about a better way with K8s RBAC stuff
# (see https://github.com/stackabletech/t2/issues/119)
- hosts: all
  vars_prompt:
    - name: input_aws_access_key
      prompt: aws_access_key
    - name: input_aws_secret_access_key
      prompt: aws_secret_access_key
  roles: 
  - role: common
    aws_access_key: "{{input_aws_access_key}}"
    aws_secret_access_key: "{{input_aws_secret_access_key}}"

- hosts: orchestrator
  roles:
  - orchestrator

- hosts: nodes
  roles:
  - agent