# Some common settings for CentOS nodes
# 
# - hostname
# - transparent hugepages disabled
# - SELinux disabled
# - IPv6 disabled
---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}.{{ domain }}"

# (caused errors in HCloud CentOS 8) 
#
#- name: Ensure that Transparent Hugepages are disabled
#  lineinfile:
#    dest: /etc/default/grub
#    line: GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX transparent_hugepage=never"
#    state: present
#  notify:
#    - update grub
#    - reboot

- name: Ensure SELinux is disabled
  selinux:
    state: disabled
  notify: reboot

- name: Ensure that IPv6 is disabled
  lineinfile:
    dest: /etc/default/grub
    line: GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX ipv6.disable=1"
    state: present
  notify: reboot

- name: Ensure that common sysctl tunables are set
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    ignoreerrors: yes
  loop:
    - { name: 'vm.swappiness', value: 1 }

- name: Update facts to reflect new hostname
  setup: