# Install k9s tool
# https://k9scli.io/
---
- name: install k9s
  unarchive:
    src: https://github.com/derailed/k9s/releases/download/v0.24.9/k9s_Linux_x86_64.tar.gz
    remote_src: yes
    dest: /usr/local/bin
    mode: 0755
    exclude:
      - LICENSE
      - README.md
