name: Test, Build and Scan

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test-build-scan:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run tests
        run: mvn -B test --file pom.xml

      - name: Package Java app
        run: mvn -B package --file pom.xml

      - name: Build T2 image
        run: |
          docker build -t docker.stackable.tech/t2:${{ github.sha }} .

      - name: Create report folder
        run: |
          mkdir -p report/

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.stackable.tech/t2:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: false
          vuln-type: 'os,library'
          # severity: 'CRITICAL,HIGH'
          output: "report/trivy-report.txt"

      - id: get-trivy-report
        run: |
          report="$(cat report/trivy-report.txt)"
          report="${report//'%'/'%25'}"
          report="${report//$'\n'/'%0A'}"
          report="${report//$'\r'/'%0D'}" 
          echo "::set-output name=report::$report"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.STACKY_MC_STACKFACE_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Trivy vulnerability report**
            
            ```
            ${{ steps.get-trivy-report.outputs.report }}
            ```
