# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Trigger integration test with token now... repo access public only
      env:
        IT_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      run: |
        curl \
          -X POST \
          -u "backstreetkiwi:$IT_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/stackabletech/pit/actions/workflows/webhook.yml/dispatches\
          -d '{"ref":"main"}'



  