name: Test, Build and Scan

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test-build-scan:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

#      - name: create report
#        id: create-report
#        run: |
#          cat Dockerfile

      - name: Read file contents
        id: create_report
        uses: andstor/file-reader-action@v1
        with:
          path: "Dockerfile"

#      - name: File contents
#        run: echo `${{ steps.create_report.outputs.contents }}`

      - uses: actions/github-script@v6
        env:
          BODY: "${{GITHUB_WORKFLOW}}"
        with:
          github-token: ${{secrets.STACKY_MC_STACKFACE_TOKEN}}
          script: |
            const { BODY } = process.env
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${BODY}`
            })




