name: Trivy Spike

on:
  workflow_dispatch:

jobs:

  t2-testdriver:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Build T2 image
        run: |
          docker build -t docker.stackable.tech/t2:${{ github.sha }} .
