name: Publish AvailableVersions script in Docker

on:
  workflow_dispatch:

jobs:

  t2-available-versions:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - run: |
          echo "hallo hurz" > ./hallo.txt
          ls -la .

#      - uses: docker/login-action@v1
#        with:
#          registry: docker.stackable.tech
#          username: github
#          password: ${{ secrets.NEXUS_PASSWORD }}
#
#      - uses: docker/build-push-action@v2.4.0
#        with:
#          context: available-versions/
#          tags: docker.stackable.tech/t2-available-versions:latest
#          push: true
