name: Trivy Spike

on:
  workflow_dispatch:

jobs:

  trivy-spike:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Package T2
        run: mvn -B package --file pom.xml

      - name: Build T2 image
        run: |
          docker build -t docker.stackable.tech/t2:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.stackable.tech/t2:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: false
          vuln-type: 'os,library'
          # severity: 'CRITICAL,HIGH'
          output: "report/trivy-report.txt"

      - name: archive artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: trivy-report
          path: report
