# Collect facts about the network
# 
# - public_network_interface_name  (only 'edge' node)
# - private_network_interface_name (all nodes)
---
- name: determine public network interface for edge node
  shell: "ip -4 -o a | grep '{{ ansible_host }}' | head -1 | cut -d ' ' -f 2"
  register: public_ip_output_edge
  when: "'edge' == inventory_hostname"

- name: determine private network interface for edge node
  shell: "ip -4 -o a | grep '{{ internal_ip }}' | head -1 | cut -d ' ' -f 2"
  register: private_ip_output_edge
  when: "'edge' == inventory_hostname"

- name: determine private network interface for protected nodes
  shell: "ip -4 -o a | grep '{{ ansible_host }}' | head -1 | cut -d ' ' -f 2"
  register: private_ip_output_protected
  when: "'edge' != inventory_hostname"

- name: set public network interface as Ansible fact (edge node)
  set_fact:
    public_network_interface_name: "{{ public_ip_output_edge.stdout }}"
  when: "'edge' == inventory_hostname"

- name: set private network interface as Ansible fact (edge node)
  set_fact:
    private_network_interface_name: "{{ private_ip_output_edge.stdout }}"
  when: "'edge' == inventory_hostname"

- name: set private network interface as Ansible fact (protected nodes)
  set_fact:
    private_network_interface_name: "{{ private_ip_output_protected.stdout }}"
  when: "'edge' != inventory_hostname"
